### ISSUE TITLE
KeyError: 'ImageDataset'

### ISSUE THREAD

**Issue by kangzejian1896** [geopavlakos/hamer#40]
Thank you for your open-source work, it works very well! I encountered the following problem when I run 

> python train.py exp_name=hamer data=mix_all experiment=hamer_vit_transformer trainer=gpu launcher=local

```

Error executing job with overrides: ['exp_name=hamer', 'data=mix_all', 'experiment=hamer_vit_transformer', 'trainer=gpu', 'launcher=local']
Traceback (most recent call last):
  File "/mnt/nfs/MotionDriven/FINGER_REPAIRE/HaMeR/train.py", line 109, in main
    train(cfg)
  File "/mnt/nfs/MotionDriven/FINGER_REPAIRE/HaMeR/hamer/utils/misc.py", line 42, in wrap
    raise ex
  File "/mnt/nfs/MotionDriven/FINGER_REPAIRE/HaMeR/hamer/utils/misc.py", line 39, in wrap
    ret = task_func(cfg=cfg)
  File "/mnt/nfs/MotionDriven/FINGER_REPAIRE/HaMeR/train.py", line 102, in train
    trainer.fit(model, datamodule=datamodule, ckpt_path='last')
  File "/ssd/home/anaconda3/envs/hamer/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/ssd/home/anaconda3/envs/hamer/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/ssd/home/anaconda3/envs/hamer/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/ssd/home/anaconda3/envs/hamer/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 949, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/ssd/home/anaconda3/envs/hamer/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/ssd/home/anaconda3/envs/hamer/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/mnt/nfs/MotionDriven/FINGER_REPAIRE/HaMeR/hamer/datasets/__init__.py", line 57, in setup
    self.train_dataset = MixedWebDataset(self.cfg, self.dataset_cfg, train=True).with_epoch(100_000).shuffle(4000)
  File "/mnt/nfs/MotionDriven/FINGER_REPAIRE/HaMeR/hamer/datasets/__init__.py", line 28, in __init__
    datasets = [create_webdataset(cfg, dataset_cfg[dataset], train=train) for dataset, v in dataset_list.items()]
  File "/mnt/nfs/MotionDriven/FINGER_REPAIRE/HaMeR/hamer/datasets/__init__.py", line 28, in <listcomp>
    datasets = [create_webdataset(cfg, dataset_cfg[dataset], train=train) for dataset, v in dataset_list.items()]
  File "/mnt/nfs/MotionDriven/FINGER_REPAIRE/HaMeR/hamer/datasets/__init__.py", line 20, in create_webdataset
    dataset_type = Dataset.registry[dataset_cfg.TYPE]
KeyError: 'ImageDataset'
```

How can I fix it? Thank you

**Comment by geopavlakos** [comment]
Hmm, I don't recognize this error.
Is is possible that you haven't downloaded the training data properly?
