### ISSUE TITLE
demo.py doesn't work with Docker compose 

### ISSUE THREAD

**Issue by SamChonCLO** [geopavlakos/hamer#75]
I have tried with docker compose with your dockerfile
I got an error about OpenGL

`
```
root@0658d4e7f4db:/app# python demo.py \
--img_folder example_data --out_folder demo_out \
--batch_size=48 --side_view --save_mesh
Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/OpenGL/platform/egl.py", line 67, in EGL
    return ctypesloader.loadLibrary(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/OpenGL/platform/ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: ('EGL: cannot open shared object file: No such file or directory', 'EGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/demo.py", line 9, in <module>
    from hamer.models import HAMER, download_models, load_hamer, DEFAULT_CHECKPOINT
  File "/app/hamer/models/__init__.py", line 2, in <module>
    from .hamer import HAMER
  File "/app/hamer/models/hamer.py", line 7, in <module>
    from ..utils import SkeletonRenderer, MeshRenderer
  File "/app/hamer/utils/__init__.py", line 4, in <module>
    from .renderer import Renderer
  File "/app/hamer/utils/renderer.py", line 6, in <module>
    import pyrender
  File "/opt/venv/lib/python3.12/site-packages/pyrender/__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "/opt/venv/lib/python3.12/site-packages/pyrender/light.py", line 10, in <module>
    from OpenGL.GL import *
  File "/opt/venv/lib/python3.12/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/opt/venv/lib/python3.12/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/opt/venv/lib/python3.12/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/opt/venv/lib/python3.12/site-packages/OpenGL/platform/__init__.py", line 32, in _load
    plugin.install(globals())
  File "/opt/venv/lib/python3.12/site-packages/OpenGL/platform/baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
            ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/OpenGL/platform/egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
           ^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
            ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/OpenGL/platform/egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', 'EGL: cannot open shared object file: No such file or directory', 'EGL', None)
```

'

**Comment by ntvthuyen** [comment]
Please run
``` apt-get update && apt-get install ffmpeg libsm6 libxext6  -y ```
``` apt-get install libglfw3-dev libgles2-mesa-dev ```

**Comment by geopavlakos** [comment]
There have been some recent commits from @Kaszanas and @ntvthuyen that have improved the docker functionality. Could you please give the code a try after these updates.

**Comment by Kaszanas** [comment]
> There have been some recent commits from @Kaszanas and @ntvthuyen that have improved the docker functionality. Could you please give the code a try after these updates.

At this point Docker:
#WorksOnMyMachine
